export type Student = {
  regNo: string;
  rollNo: number;
  name: string;
  className: string;
  attendance: number;
  marks: { english: number; math: number; science: number; ssc: number; python: number };
  total: number;
  percentage: number;
  grade: string;
  remarks: string;
  avatar: string;
  parentName: string;
  parentEmail: string;
  guardian: string;
};

const FIRST = ["Aarav","Vivaan","Aditya","Diya","Ananya","Ishaan","Kabir","Saanvi","Myra","Reyansh","Aanya","Arjun","Krishna","Ira","Anika","Riaan","Vihaan","Pari","Sara","Rudra","Kiara","Ayaan","Zara","Dev","Nisha","Rohan","Tara","Yash","Maya","Veer"];
const LAST = ["Sharma","Verma","Iyer","Gupta","Patel","Nair","Reddy","Mehta","Singh","Khan","Bose","Das","Joshi","Pillai","Kapoor"];
const CLASSES = ["10-A","10-B","9-A","9-B","8-A","8-B"];

function seeded(i: number) { const x = Math.sin(i * 9301 + 49297) * 233280; return x - Math.floor(x); }
function pick<T>(arr: T[], i: number) { return arr[Math.floor(seeded(i) * arr.length)]; }
function gradeFor(p: number) { return p >= 90 ? "A+" : p >= 80 ? "A" : p >= 70 ? "B" : p >= 60 ? "C" : p >= 50 ? "D" : "F"; }
function remarkFor(p: number, att: number) {
  if (p >= 85 && att >= 90) return "Outstanding performer with excellent consistency.";
  if (p >= 70) return "Strong overall, push harder on weaker subjects.";
  if (att < 75) return "Attendance dipping — risk of falling behind.";
  if (p < 50) return "Needs immediate intervention and personalized plan.";
  return "Steady progress, room to grow with focused practice.";
}

export const students: Student[] = Array.from({ length: 48 }, (_, idx) => {
  const i = idx + 1;
  const first = pick(FIRST, i);
  const last = pick(LAST, i + 7);
  const name = `${first} ${last}`;
  const className = pick(CLASSES, i + 3);
  const attendance = Math.round(60 + seeded(i + 11) * 40);
  const eng = Math.round(40 + seeded(i + 21) * 60);
  const math = Math.round(40 + seeded(i + 22) * 60);
  const sci = Math.round(40 + seeded(i + 23) * 60);
  const ssc = Math.round(40 + seeded(i + 24) * 60);
  const py = Math.round(40 + seeded(i + 25) * 60);
  const total = eng + math + sci + ssc + py;
  const percentage = Math.round((total / 500) * 1000) / 10;
  return {
    regNo: `REG${(2024000 + i).toString()}`,
    rollNo: i,
    name,
    className,
    attendance,
    marks: { english: eng, math, science: sci, ssc, python: py },
    total,
    percentage,
    grade: gradeFor(percentage),
    remarks: remarkFor(percentage, attendance),
    avatar: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(name)}&backgroundType=gradientLinear`,
    parentName: `${pick(FIRST, i + 30)} ${last}`,
    parentEmail: `${first.toLowerCase()}.parent@school.edu`,
    guardian: pick(["Father","Mother","Guardian"], i + 5),
  };
});

export const attendanceTrend = [
  { month: "Apr", attendance: 92 },
  { month: "May", attendance: 89 },
  { month: "Jun", attendance: 87 },
  { month: "Jul", attendance: 91 },
  { month: "Aug", attendance: 88 },
  { month: "Sep", attendance: 84 },
  { month: "Oct", attendance: 86 },
  { month: "Nov", attendance: 90 },
];

export const monthlyPerformance = [
  { month: "Apr", avg: 72, top: 94 },
  { month: "May", avg: 74, top: 95 },
  { month: "Jun", avg: 71, top: 92 },
  { month: "Jul", avg: 76, top: 96 },
  { month: "Aug", avg: 78, top: 97 },
  { month: "Sep", avg: 75, top: 95 },
  { month: "Oct", avg: 80, top: 98 },
  { month: "Nov", avg: 82, top: 99 },
];

export const subjectAverage = [
  { subject: "English", avg: Math.round(students.reduce((a, s) => a + s.marks.english, 0) / students.length) },
  { subject: "Math", avg: Math.round(students.reduce((a, s) => a + s.marks.math, 0) / students.length) },
  { subject: "Science", avg: Math.round(students.reduce((a, s) => a + s.marks.science, 0) / students.length) },
  { subject: "SSC", avg: Math.round(students.reduce((a, s) => a + s.marks.ssc, 0) / students.length) },
  { subject: "Python", avg: Math.round(students.reduce((a, s) => a + s.marks.python, 0) / students.length) },
];

export const notifications = [
  { id: 1, type: "alert" as const, title: "Low attendance alert", body: "12 students dropped below 75% this week.", time: "2h ago" },
  { id: 2, type: "warning" as const, title: "Failed subjects flagged", body: "5 students scored below 50% in Math.", time: "5h ago" },
  { id: 3, type: "info" as const, title: "Upcoming test", body: "Science unit test scheduled on Nov 22.", time: "1d ago" },
  { id: 4, type: "success" as const, title: "Top performer", body: "Class 10-A average crossed 85%.", time: "2d ago" },
  { id: 5, type: "info" as const, title: "Monthly report ready", body: "October report generated by AI.", time: "3d ago" },
];

export const aiInsights = [
  { title: "Attendance risk detected", body: "8 students show a downward attendance trend over 3 weeks. Suggest parent-teacher follow-up.", tone: "warning" as const },
  { title: "Math weak cluster", body: "Class 9-A averages 58% in Math — recommend targeted practice modules and weekly quizzes.", tone: "alert" as const },
  { title: "Strength: Python aptitude", body: "Top 20% students excel in Python — consider an advanced coding club.", tone: "success" as const },
  { title: "Personalized tip", body: "For mid-tier performers, 20-min daily revision improves outcomes by ~12%.", tone: "info" as const },
];

export function getStudent(regNo: string) {
  return students.find((s) => s.regNo === regNo);
}
