/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountantRouteImport } from './routes/accountant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransportIndexRouteImport } from './routes/transport.index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountantIndexRouteImport } from './routes/accountant.index'
import { Route as TransportRoutesRouteImport } from './routes/transport.routes'
import { Route as TransportAssignmentsRouteImport } from './routes/transport.assignments'
import { Route as TeacherTimetableRouteImport } from './routes/teacher.timetable'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentsRegNoRouteImport } from './routes/students.$regNo'
import { Route as StudentTransportRouteImport } from './routes/student.transport'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as ApiN8nFetchRouteImport } from './routes/api/n8n-fetch'
import { Route as ApiN8nChatRouteImport } from './routes/api/n8n-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminTransportRouteImport } from './routes/admin.transport'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AccountantReportsRouteImport } from './routes/accountant.reports'
import { Route as AccountantPaymentsRouteImport } from './routes/accountant.payments'
import { Route as AccountantFeesRouteImport } from './routes/accountant.fees'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRoute = AccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportIndexRoute = TransportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransportRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountantIndexRoute = AccountantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountantRoute,
} as any)
const TransportRoutesRoute = TransportRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => TransportRoute,
} as any)
const TransportAssignmentsRoute = TransportAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TransportRoute,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentsRegNoRoute = StudentsRegNoRouteImport.update({
  id: '/$regNo',
  path: '/$regNo',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentTransportRoute = StudentTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const ApiN8nFetchRoute = ApiN8nFetchRouteImport.update({
  id: '/api/n8n-fetch',
  path: '/api/n8n-fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nChatRoute = ApiN8nChatRouteImport.update({
  id: '/api/n8n-chat',
  path: '/api/n8n-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AccountantReportsRoute = AccountantReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AccountantRoute,
} as any)
const AccountantPaymentsRoute = AccountantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountantRoute,
} as any)
const AccountantFeesRoute = AccountantFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AccountantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/accountant/fees': typeof AccountantFeesRoute
  '/accountant/payments': typeof AccountantPaymentsRoute
  '/accountant/reports': typeof AccountantReportsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/transport': typeof AdminTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/api/n8n-fetch': typeof ApiN8nFetchRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/students/$regNo': typeof StudentsRegNoRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/transport/assignments': typeof TransportAssignmentsRoute
  '/transport/routes': typeof TransportRoutesRoute
  '/accountant/': typeof AccountantIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/transport/': typeof TransportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRouteWithChildren
  '/accountant/fees': typeof AccountantFeesRoute
  '/accountant/payments': typeof AccountantPaymentsRoute
  '/accountant/reports': typeof AccountantReportsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/transport': typeof AdminTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/api/n8n-fetch': typeof ApiN8nFetchRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/students/$regNo': typeof StudentsRegNoRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/transport/assignments': typeof TransportAssignmentsRoute
  '/transport/routes': typeof TransportRoutesRoute
  '/accountant': typeof AccountantIndexRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/transport': typeof TransportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/transport': typeof TransportRouteWithChildren
  '/accountant/fees': typeof AccountantFeesRoute
  '/accountant/payments': typeof AccountantPaymentsRoute
  '/accountant/reports': typeof AccountantReportsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/transport': typeof AdminTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/api/n8n-fetch': typeof ApiN8nFetchRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/students/$regNo': typeof StudentsRegNoRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/transport/assignments': typeof TransportAssignmentsRoute
  '/transport/routes': typeof TransportRoutesRoute
  '/accountant/': typeof AccountantIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/transport/': typeof TransportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant'
    | '/admin'
    | '/insights'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/signup'
    | '/student'
    | '/students'
    | '/teacher'
    | '/transport'
    | '/accountant/fees'
    | '/accountant/payments'
    | '/accountant/reports'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/transport'
    | '/api/chat'
    | '/api/n8n-chat'
    | '/api/n8n-fetch'
    | '/student/attendance'
    | '/student/fees'
    | '/student/results'
    | '/student/timetable'
    | '/student/transport'
    | '/students/$regNo'
    | '/teacher/attendance'
    | '/teacher/results'
    | '/teacher/timetable'
    | '/transport/assignments'
    | '/transport/routes'
    | '/accountant/'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/transport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/signup'
    | '/students'
    | '/accountant/fees'
    | '/accountant/payments'
    | '/accountant/reports'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/transport'
    | '/api/chat'
    | '/api/n8n-chat'
    | '/api/n8n-fetch'
    | '/student/attendance'
    | '/student/fees'
    | '/student/results'
    | '/student/timetable'
    | '/student/transport'
    | '/students/$regNo'
    | '/teacher/attendance'
    | '/teacher/results'
    | '/teacher/timetable'
    | '/transport/assignments'
    | '/transport/routes'
    | '/accountant'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/accountant'
    | '/admin'
    | '/insights'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/signup'
    | '/student'
    | '/students'
    | '/teacher'
    | '/transport'
    | '/accountant/fees'
    | '/accountant/payments'
    | '/accountant/reports'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/transport'
    | '/api/chat'
    | '/api/n8n-chat'
    | '/api/n8n-fetch'
    | '/student/attendance'
    | '/student/fees'
    | '/student/results'
    | '/student/timetable'
    | '/student/transport'
    | '/students/$regNo'
    | '/teacher/attendance'
    | '/teacher/results'
    | '/teacher/timetable'
    | '/transport/assignments'
    | '/transport/routes'
    | '/accountant/'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/transport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantRoute: typeof AccountantRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  StudentsRoute: typeof StudentsRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TransportRoute: typeof TransportRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiN8nChatRoute: typeof ApiN8nChatRoute
  ApiN8nFetchRoute: typeof ApiN8nFetchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant': {
      id: '/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AccountantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/': {
      id: '/transport/'
      path: '/'
      fullPath: '/transport/'
      preLoaderRoute: typeof TransportIndexRouteImport
      parentRoute: typeof TransportRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accountant/': {
      id: '/accountant/'
      path: '/'
      fullPath: '/accountant/'
      preLoaderRoute: typeof AccountantIndexRouteImport
      parentRoute: typeof AccountantRoute
    }
    '/transport/routes': {
      id: '/transport/routes'
      path: '/routes'
      fullPath: '/transport/routes'
      preLoaderRoute: typeof TransportRoutesRouteImport
      parentRoute: typeof TransportRoute
    }
    '/transport/assignments': {
      id: '/transport/assignments'
      path: '/assignments'
      fullPath: '/transport/assignments'
      preLoaderRoute: typeof TransportAssignmentsRouteImport
      parentRoute: typeof TransportRoute
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/students/$regNo': {
      id: '/students/$regNo'
      path: '/$regNo'
      fullPath: '/students/$regNo'
      preLoaderRoute: typeof StudentsRegNoRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/student/transport': {
      id: '/student/transport'
      path: '/transport'
      fullPath: '/student/transport'
      preLoaderRoute: typeof StudentTransportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/n8n-fetch': {
      id: '/api/n8n-fetch'
      path: '/api/n8n-fetch'
      fullPath: '/api/n8n-fetch'
      preLoaderRoute: typeof ApiN8nFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n-chat': {
      id: '/api/n8n-chat'
      path: '/api/n8n-chat'
      fullPath: '/api/n8n-chat'
      preLoaderRoute: typeof ApiN8nChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accountant/reports': {
      id: '/accountant/reports'
      path: '/reports'
      fullPath: '/accountant/reports'
      preLoaderRoute: typeof AccountantReportsRouteImport
      parentRoute: typeof AccountantRoute
    }
    '/accountant/payments': {
      id: '/accountant/payments'
      path: '/payments'
      fullPath: '/accountant/payments'
      preLoaderRoute: typeof AccountantPaymentsRouteImport
      parentRoute: typeof AccountantRoute
    }
    '/accountant/fees': {
      id: '/accountant/fees'
      path: '/fees'
      fullPath: '/accountant/fees'
      preLoaderRoute: typeof AccountantFeesRouteImport
      parentRoute: typeof AccountantRoute
    }
  }
}

interface AccountantRouteChildren {
  AccountantFeesRoute: typeof AccountantFeesRoute
  AccountantPaymentsRoute: typeof AccountantPaymentsRoute
  AccountantReportsRoute: typeof AccountantReportsRoute
  AccountantIndexRoute: typeof AccountantIndexRoute
}

const AccountantRouteChildren: AccountantRouteChildren = {
  AccountantFeesRoute: AccountantFeesRoute,
  AccountantPaymentsRoute: AccountantPaymentsRoute,
  AccountantReportsRoute: AccountantReportsRoute,
  AccountantIndexRoute: AccountantIndexRoute,
}

const AccountantRouteWithChildren = AccountantRoute._addFileChildren(
  AccountantRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminTransportRoute: typeof AdminTransportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminTransportRoute: AdminTransportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentTransportRoute: typeof StudentTransportRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentTransportRoute: StudentTransportRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface StudentsRouteChildren {
  StudentsRegNoRoute: typeof StudentsRegNoRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsRegNoRoute: StudentsRegNoRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherResultsRoute: typeof TeacherResultsRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherResultsRoute: TeacherResultsRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

interface TransportRouteChildren {
  TransportAssignmentsRoute: typeof TransportAssignmentsRoute
  TransportRoutesRoute: typeof TransportRoutesRoute
  TransportIndexRoute: typeof TransportIndexRoute
}

const TransportRouteChildren: TransportRouteChildren = {
  TransportAssignmentsRoute: TransportAssignmentsRoute,
  TransportRoutesRoute: TransportRoutesRoute,
  TransportIndexRoute: TransportIndexRoute,
}

const TransportRouteWithChildren = TransportRoute._addFileChildren(
  TransportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantRoute: AccountantRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  StudentsRoute: StudentsRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TransportRoute: TransportRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiN8nChatRoute: ApiN8nChatRoute,
  ApiN8nFetchRoute: ApiN8nFetchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
