/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountantRouteImport } from './routes/accountant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsRegNoRouteImport } from './routes/students.$regNo'
import { Route as ApiN8nFetchRouteImport } from './routes/api/n8n-fetch'
import { Route as ApiN8nChatRouteImport } from './routes/api/n8n-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminTransportRouteImport } from './routes/admin.transport'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRoute = AccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRegNoRoute = StudentsRegNoRouteImport.update({
  id: '/$regNo',
  path: '/$regNo',
  getParentRoute: () => StudentsRoute,
} as any)
const ApiN8nFetchRoute = ApiN8nFetchRouteImport.update({
  id: '/api/n8n-fetch',
  path: '/api/n8n-fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nChatRoute = ApiN8nChatRouteImport.update({
  id: '/api/n8n-chat',
  path: '/api/n8n-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/admin': typeof AdminRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRouteWithChildren
  '/teacher': typeof TeacherRoute
  '/transport': typeof TransportRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/transport': typeof AdminTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/api/n8n-fetch': typeof ApiN8nFetchRoute
  '/students/$regNo': typeof StudentsRegNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/admin': typeof AdminRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRouteWithChildren
  '/teacher': typeof TeacherRoute
  '/transport': typeof TransportRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/transport': typeof AdminTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/api/n8n-fetch': typeof ApiN8nFetchRoute
  '/students/$regNo': typeof StudentsRegNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRoute
  '/admin': typeof AdminRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRouteWithChildren
  '/teacher': typeof TeacherRoute
  '/transport': typeof TransportRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/transport': typeof AdminTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/api/n8n-fetch': typeof ApiN8nFetchRoute
  '/students/$regNo': typeof StudentsRegNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant'
    | '/admin'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/signup'
    | '/student'
    | '/students'
    | '/teacher'
    | '/transport'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/transport'
    | '/api/chat'
    | '/api/n8n-chat'
    | '/api/n8n-fetch'
    | '/students/$regNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountant'
    | '/admin'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/signup'
    | '/student'
    | '/students'
    | '/teacher'
    | '/transport'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/transport'
    | '/api/chat'
    | '/api/n8n-chat'
    | '/api/n8n-fetch'
    | '/students/$regNo'
  id:
    | '__root__'
    | '/'
    | '/accountant'
    | '/admin'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/signup'
    | '/student'
    | '/students'
    | '/teacher'
    | '/transport'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/classes'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/transport'
    | '/api/chat'
    | '/api/n8n-chat'
    | '/api/n8n-fetch'
    | '/students/$regNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantRoute: typeof AccountantRoute
  AdminRoute: typeof AdminRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  TeacherRoute: typeof TeacherRoute
  TransportRoute: typeof TransportRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiN8nChatRoute: typeof ApiN8nChatRoute
  ApiN8nFetchRoute: typeof ApiN8nFetchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant': {
      id: '/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AccountantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$regNo': {
      id: '/students/$regNo'
      path: '/$regNo'
      fullPath: '/students/$regNo'
      preLoaderRoute: typeof StudentsRegNoRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/api/n8n-fetch': {
      id: '/api/n8n-fetch'
      path: '/api/n8n-fetch'
      fullPath: '/api/n8n-fetch'
      preLoaderRoute: typeof ApiN8nFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n-chat': {
      id: '/api/n8n-chat'
      path: '/api/n8n-chat'
      fullPath: '/api/n8n-chat'
      preLoaderRoute: typeof ApiN8nChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminTransportRoute: typeof AdminTransportRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminTransportRoute: AdminTransportRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentsRouteChildren {
  StudentsRegNoRoute: typeof StudentsRegNoRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsRegNoRoute: StudentsRegNoRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantRoute: AccountantRoute,
  AdminRoute: AdminRouteWithChildren,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRoute,
  StudentsRoute: StudentsRouteWithChildren,
  TeacherRoute: TeacherRoute,
  TransportRoute: TransportRoute,
  ApiChatRoute: ApiChatRoute,
  ApiN8nChatRoute: ApiN8nChatRoute,
  ApiN8nFetchRoute: ApiN8nFetchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
